#include <xalTypes.h>
#include <xArchTypeIfc.h>
#include <xAsmIfc.h>
#include <xBoardTypeIfc.h>
#include <xcfTypeIfc.h>
#include <xCommPortIfc.h>
#include <xHealthMonitorIfc.h>
#include <xLegacyIfc.h>
#include <xPartitionIfc.h>
#include <xQueuingPortIfc.h>
#include <xSamplingPortIfc.h>
#include <xScheduleIfc.h>
//#include <xTraceIfc.h>
#include <xTypeIfc.h>
#include <xVClockIfc.h>
#include <xVCpuIfc.h>
#include <xVIrqCtrlIfc.h>
#include <xVTimerIfc.h>
