//#include <types.h>
//#include <ske_init.h>
//#include <ske_irq.h>
//#include <ske_partition.h>
//#include <ske_queuing_port.h>
//#include <ske_sampling_port.h>
//#include <ske_time.h>
//#include <ske_trace.h>
//#include <ske_types.h>
#include <xalCpuIfc.h>
#include <xalTypesIfc.h>
#include <xArchTypeIfc.h>
#include <xAsmIfc.h>
#include <xBoardTypeIfc.h>
#include <xcfTypeIfc.h>
#include <xCommPortIfc.h>
//#include <xHealthMonitorIfc.h>
#include <xLegacyIfc.h>
#include <xPartitionIfc.h>
#include <xQueuingPortIfc.h>
#include <xSamplingPortIfc.h>
#include <xScheduleIfc.h>
#include <xTraceIfc.h>
#include <xTypeIfc.h>
#include <xVClockIfc.h>
#include <xVCpuIfc.h>
#include <xVIrqCtrlIfc.h>
#include <xVTimerIfc.h>
