name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  C_INCLUDE_PATH: $GITHUB_WORKSPACE/include

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - uses: mbrobbel/rustfmt-check@0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract XNG headers
        run: echo "${{ secrets.XNG_HEADER_0 }}" | base64 --decode > XNG_HEADER_0;
             echo "${{ secrets.XNG_HEADER_1 }}" | base64 --decode > XNG_HEADER_1;
             cat XNG_HEADER_0 XNG_HEADER_1 | tar --zstd -xv
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Run tests
        run: cargo test --no-default-features --verbose

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract XNG headers
        run: echo "${{ secrets.XNG_HEADER_0 }}" | base64 --decode > XNG_HEADER_0;
             echo "${{ secrets.XNG_HEADER_1 }}" | base64 --decode > XNG_HEADER_1;
             cat XNG_HEADER_0 XNG_HEADER_1 | tar --zstd -xv
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
